In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path

import pandas as pd

from magneton.utils import get_data_dir

In [3]:
labels_dir = get_data_dir() / "interpro_103.0" / "labels"

In [15]:
all_counts = []
for label_dir in labels_dir.iterdir():
    counts = []
    for label_set in label_dir.iterdir():
        num_labels = len(pd.read_table(label_set))
        label_type = label_set.stem.replace(".labels", "")
        counts.append((label_type, num_labels))
    counts = pd.DataFrame(counts, columns=["interpro_type", "count"]).assign(
        label_set=label_dir.stem
    )
    all_counts.append(counts)

In [20]:
all_counts = pd.concat(all_counts)

In [22]:
df = pd.pivot_table(data=all_counts, index="interpro_type", columns="label_set")
df

                          count                                           \
label_set              full_set selected_subset selected_subset_cutoff10
interpro_type
Active_site               133.0            82.0                    127.0
Binding_site               76.0            48.0                     74.0
Conserved_site            748.0           356.0                    691.0
Domain                  15868.0           917.0                   3506.0
Family                  26322.0          1353.0                   6524.0
Homologous_superfamily   3511.0          1133.0                   2159.0
PTM                        17.0             6.0                     13.0
Repeat                    374.0             NaN                      NaN


label_set              selected_subset_cutoff25
interpro_type
Active_site                               114.0
Binding_site                               72.0
Conserved_site                            573.0
Domain                                   1964.0
Family                                   3400.0
Homologous_superfamily                   1685.0
PTM                                         9.0
Repeat                                      NaN

In [28]:
df.columns = df.columns.droplevel()
df

label_set,full_set,selected_subset,selected_subset_cutoff10,selected_subset_cutoff25
interpro_type,,,,
Active_site,133.0,82.0,127.0,114.0
Binding_site,76.0,48.0,74.0,72.0
Conserved_site,748.0,356.0,691.0,573.0
Domain,15868.0,917.0,3506.0,1964.0
Family,26322.0,1353.0,6524.0,3400.0
Homologous_superfamily,3511.0,1133.0,2159.0,1685.0
PTM,17.0,6.0,13.0,9.0
Repeat,374.0,NaN,NaN,NaN

In [34]:
row_order = [
    "Homologous_superfamily",
    "Domain",
    "Conserved_site",
    "Binding_site",
    "Active_site",
]
col_order = [
    "full_set",
    "selected_subset",
    "selected_subset_cutoff25",
    "selected_subset_cutoff10",
]
for_display = (
    df.loc[row_order, col_order]
    .astype(int)
    .rename(
        columns={
            "full_set": "Full SwissProt set",
            "selected_subset": "Count >= 75",
            "selected_subset_cutoff25": "Count >= 25",
            "selected_subset_cutoff10": "Count >= 10",
        },
        index=lambda x: x.replace("_", " "),
    )
)
for_display

label_set,Full SwissProt set,Count >= 75,Count >= 25,Count >= 10
interpro_type,,,,
Homologous superfamily,3511,1133,1685,2159
Domain,15868,917,1964,3506
Conserved site,748,356,573,691
Binding site,76,48,72,74
Active site,133,82,114,127

In [2]:
import os

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
import bz2
import logging
import pickle
import tempfile
from functools import partial

import fire
import requests
from magneton.types import Protein

from magneton.io.internal import (
    parse_from_pkl,
    process_sharded_proteins,
)
from magneton.io.mmcif import mmcif_to_secondary_structs

In [34]:
# Replace with your path to the magneton-data huggingface dataset
data_path = Path("/weka/scratch/weka/kellislab/rcalef/data/magneton-data")


fasta_path = data_path / "sequences" / "uniprot_sprot.fasta.gz"

In [36]:
pkl_path = (
    data_path
    / "interpro_103.0"
    / "seq_splits"
    / "train_sharded"
    / "swissprot.with_ss.train.0.pkl.bz2"
)
pkl_path = Path(
    "/weka/scratch/weka/kellislab/rcalef/data/interpro/103.0/parsed_pickles/sharded_proteins.0.pkl.bz2"
)

example_prots = []
for i, prot in enumerate(parse_from_pkl(pkl_path)):
    example_prots.append(prot)
    if i == 10:
        break

# The `print()` method just pretty prints the object.
example_prots[0].print()

Protein(uniprot_id='A0A000',
        kb_id='sp|A0A000|A0A000_STRVD',
        name='A0A000_STRVD',
        length=394,
        parsed_entries=6,
        total_entries=7,
        entries=[InterproEntry(id='IPR015421',
                               element_type='Homologous_superfamily',
                               match_id='G3DSA:3.40.640.10',
                               element_name='Pyridoxal phosphate-dependent '
                                            'transferase, major domain',
                               representative=False,
                               positions=[(48, 288)]),
                 InterproEntry(id='IPR015422',
                               element_type='Homologous_superfamily',
                               match_id='G3DSA:3.90.1150.10',
                               element_name='Pyridoxal phosphate-dependent '
                                            'transferase, small domain',
                               representative=False,
                               positions=[(36, 378)]),
                 InterproEntry(id='IPR004839',
                               element_type='Domain',
                               match_id='PF00155',
                               element_name='Aminotransferase, class '
                                            'I/classII, large domain',
                               representative=False,
                               positions=[(41, 381)]),
                 InterproEntry(id='IPR050087',
                               element_type='Family',
                               match_id='PTHR13693',
                               element_name='8-amino-7-oxononanoate synthase '
                                            'class-II',
                               representative=False,
                               positions=[(37, 382)]),
                 InterproEntry(id='IPR015424',
                               element_type='Homologous_superfamily',
                               match_id='SSF53383',
                               element_name='Pyridoxal phosphate-dependent '
                                            'transferase',
                               representative=False,
                               positions=[(9, 389)]),
                 InterproEntry(id='IPR010961',
                               element_type='Domain',
                               match_id='TIGR01821',
                               element_name='Tetrapyrrole biosynthesis, '
                                            '5-aminolevulinic acid synthase',
                               representative=True,
                               positions=[(12, 391)])],
        secondary_structs=[])

In [37]:
AFDB_TMPL = "https://alphafold.ebi.ac.uk/files/AF-%s-F1-model_v4.cif"


def download_one_afdb_file(
    fh,
    uniprot_id: str,
) -> bool:
    url = AFDB_TMPL % uniprot_id

    try:
        r = requests.get(url, timeout=20)
        if r.status_code == 200:
            print("got content")
            fh.write(r.content)
        else:
            return False
    except Exception as e:
        print(f"downloading afdb: {e}")
        # logger.debug(f"failed to fetch AFDB file ({path}): {e}")
        return False
    return True

In [38]:
def add_secondary_structs_to_protein(
    prot: Protein,
) -> tuple[Protein, bool]:
    with tempfile.NamedTemporaryFile(suffix=".cif") as fh:
        try:
            download_one_afdb_file(fh, prot.uniprot_id)
            prot.secondary_structs = mmcif_to_secondary_structs(
                fh.name, expected_len=prot.length
            )
        except Exception as e:
            print(e)
            return prot, False
    return prot, True

In [39]:
got, worked = add_secondary_structs_to_protein(example_prots[0])
worked

got content

True

In [40]:
got.secondary_structs

[SecondaryStructure(dssp_type=<DsspType.H: 0>, start=2, end=13),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=13, end=15),
 SecondaryStructure(dssp_type=<DsspType.P: 5>, start=15, end=21),
 SecondaryStructure(dssp_type=<DsspType.E: 2>, start=22, end=24),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=25, end=27),
 SecondaryStructure(dssp_type=<DsspType.S: 7>, start=27, end=28),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=28, end=30),
 SecondaryStructure(dssp_type=<DsspType.E: 2>, start=30, end=34),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=34, end=36),
 SecondaryStructure(dssp_type=<DsspType.E: 2>, start=36, end=41),
 SecondaryStructure(dssp_type=<DsspType.S: 7>, start=41, end=43),
 SecondaryStructure(dssp_type=<DsspType.S: 7>, start=44, end=45),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=46, end=48),
 SecondaryStructure(dssp_type=<DsspType.G: 3>, start=49, end=52),
 SecondaryStructure(dssp_type=<DsspType.H: 0>, start=53, end=67),
 SecondaryStructure(dssp_type=<DsspType.S: 7>, start=68, end=69),
 SecondaryStructure(dssp_type=<DsspType.S: 7>, start=72, end=73),
 SecondaryStructure(dssp_type=<DsspType.E: 2>, start=73, end=74),
 SecondaryStructure(dssp_type=<DsspType.I: 4>, start=74, end=79),
 SecondaryStructure(dssp_type=<DsspType.H: 0>, start=81, end=92),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=92, end=96),
 SecondaryStructure(dssp_type=<DsspType.S: 7>, start=97, end=98),
 SecondaryStructure(dssp_type=<DsspType.E: 2>, start=98, end=103),
 SecondaryStructure(dssp_type=<DsspType.S: 7>, start=103, end=105),
 SecondaryStructure(dssp_type=<DsspType.H: 0>, start=105, end=117),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=117, end=119),
 SecondaryStructure(dssp_type=<DsspType.S: 7>, start=119, end=121),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=121, end=123),
 SecondaryStructure(dssp_type=<DsspType.E: 2>, start=124, end=129),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=129, end=131),
 SecondaryStructure(dssp_type=<DsspType.H: 0>, start=133, end=142),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=142, end=143),
 SecondaryStructure(dssp_type=<DsspType.E: 2>, start=145, end=150),
 SecondaryStructure(dssp_type=<DsspType.P: 5>, start=150, end=151),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=151, end=153),
 SecondaryStructure(dssp_type=<DsspType.H: 0>, start=154, end=164),
 SecondaryStructure(dssp_type=<DsspType.S: 7>, start=164, end=165),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=166, end=168),
 SecondaryStructure(dssp_type=<DsspType.S: 7>, start=168, end=169),
 SecondaryStructure(dssp_type=<DsspType.E: 2>, start=170, end=176),
 SecondaryStructure(dssp_type=<DsspType.S: 7>, start=176, end=177),
 SecondaryStructure(dssp_type=<DsspType.E: 2>, start=177, end=178),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=179, end=182),
 SecondaryStructure(dssp_type=<DsspType.E: 2>, start=184, end=185),
 SecondaryStructure(dssp_type=<DsspType.H: 0>, start=187, end=198),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=198, end=199),
 SecondaryStructure(dssp_type=<DsspType.E: 2>, start=199, end=205),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=206, end=212),
 SecondaryStructure(dssp_type=<DsspType.S: 7>, start=212, end=214),
 SecondaryStructure(dssp_type=<DsspType.G: 3>, start=214, end=217),
 SecondaryStructure(dssp_type=<DsspType.H: 0>, start=219, end=223),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=223, end=225),
 SecondaryStructure(dssp_type=<DsspType.G: 3>, start=226, end=229),
 SecondaryStructure(dssp_type=<DsspType.S: 7>, start=230, end=231),
 SecondaryStructure(dssp_type=<DsspType.E: 2>, start=231, end=236),
 SecondaryStructure(dssp_type=<DsspType.S: 7>, start=236, end=239),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=239, end=241),
 SecondaryStructure(dssp_type=<DsspType.S: 7>, start=241, end=243),
 SecondaryStructure(dssp_type=<DsspType.E: 2>, start=245, end=250),
 SecondaryStructure(dssp_type=<DsspType.H: 0>, start=251, end=261),
 SecondaryStructure(dssp_type=<DsspType.H: 0>, start=262, end=266),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=266, end=267),
 SecondaryStructure(dssp_type=<DsspType.S: 7>, start=267, end=268),
 SecondaryStructure(dssp_type=<DsspType.E: 2>, start=268, end=269),
 SecondaryStructure(dssp_type=<DsspType.P: 5>, start=269, end=272),
 SecondaryStructure(dssp_type=<DsspType.H: 0>, start=272, end=288),
 SecondaryStructure(dssp_type=<DsspType.H: 0>, start=290, end=309),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=309, end=311),
 SecondaryStructure(dssp_type=<DsspType.E: 2>, start=313, end=314),
 SecondaryStructure(dssp_type=<DsspType.S: 7>, start=314, end=315),
 SecondaryStructure(dssp_type=<DsspType.S: 7>, start=317, end=320),
 SecondaryStructure(dssp_type=<DsspType.E: 2>, start=321, end=325),
 SecondaryStructure(dssp_type=<DsspType.S: 7>, start=327, end=328),
 SecondaryStructure(dssp_type=<DsspType.H: 0>, start=328, end=343),
 SecondaryStructure(dssp_type=<DsspType.E: 2>, start=344, end=346),
 SecondaryStructure(dssp_type=<DsspType.E: 2>, start=348, end=350),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=351, end=354),
 SecondaryStructure(dssp_type=<DsspType.S: 7>, start=354, end=355),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=356, end=358),
 SecondaryStructure(dssp_type=<DsspType.E: 2>, start=360, end=364),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=367, end=369),
 SecondaryStructure(dssp_type=<DsspType.H: 0>, start=371, end=388),
 SecondaryStructure(dssp_type=<DsspType.T: 6>, start=388, end=390),
 SecondaryStructure(dssp_type=<DsspType.P: 5>, start=390, end=394)]

In [14]:
check = tempfile.NamedTemporaryFile(suffix=".cif.gz")
check

In [16]:
check.close()